Algoritmo "semnome"
// disciplina    : internet e programação web
// aluno       : thiago
// Descrição   : Algoritmos de teste
// Autor(a)    : thiago lopes dos santos
// Data atual  : 22/09/2022
Var
// Seção de Declarações das variáveis 
  x, y, z:inteiro;
  //declarando as variaveis inteiras
  
Inicio

// Seção de Comandos, procedimento, funções, operadores, etc... 
   x <- 10;
   y <- 5;
   z <-x + y;
   escreva("essa soma é ", z)

Fimalgoritmo